<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\ZLibWrapper\ZLibWrapper.csproj" />
    </ItemGroup>
</Project>
