<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogSimulator\LogSimulator.csproj" />
    <ProjectReference Include="..\ZLibWrapper\ZLibWrapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CompareNETObjects" Version="4.84.0" />
    <PackageReference Include="ErrorOr" Version="2.1.1" />
  </ItemGroup>

</Project>
